[package]
name = "gamecode-cli"
version = "0.1.0"
edition = "2024"
description = "CLI for AWS Bedrock Anthropic Claude with gamecode-tools integration"
authors = ["Your Name <your.email@example.com>"]

[dependencies]
gamecode-tools = { git = "https://github.com/navicore/gamecode-tools" }
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
aws-config = "1.6.3"
aws-sdk-bedrockruntime = "1.89.0"
aws-smithy-types = "1.2.8"
futures-util = "0.3"
